name: Release
on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          # optional: specify version kalau perlu
          # flutter-version: '3.22.3'

      # === Android SDK & licenses ===
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install build tools & platform
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (per-ABI)
        run: flutter build apk --split-per-abi

      - name: Stamp Jakarta time
        id: date
        run: echo "date=$(TZ='Asia/Jakarta' date +'%A %d-%m-%Y %T WIB')" >> $GITHUB_OUTPUT

      - name: Extract version
        id: version
        run: echo "version=$(grep '^version:' pubspec.yaml | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Generate tag
        id: tag
        run: echo "tag=v${{ steps.version.outputs.version }}-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          artifacts: build/app/outputs/flutter-apk/*.apk
          name: "v${{ steps.version.outputs.version }} - ${{ steps.date.outputs.date }}"
          body: "Published at ${{ steps.date.outputs.date }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag.outputs.tag }}
