name: Release
on:
  push:
    branches: [main, master]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Android SDK optional (kalau butuh)
      - uses: android-actions/setup-android@v3
      - run: yes | sdkmanager --licenses
      - run: sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # === SIGNING VIA GRADLE ===
      - name: Decode keystore
        run: |
          mkdir -p android/app
          echo "${{ secrets.KEY_JKS }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties
          storeFile=upload-keystore.jks
          storePassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS || 'upload' }}
          keyPassword=${{ secrets.KEY_ALIAS_PASSWORD || secrets.KEY_PASSWORD }}
          EOF

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (signed by Gradle)
        run: flutter build apk --release --split-per-abi

      - name: Get current date
        id: date
        run: echo "date=$(TZ='Asia/Jakarta' date +'%A %d-%m-%Y %T WIB')" >> $GITHUB_OUTPUT

      - name: Generate unique tag
        id: tag
        run: echo "tag=v$(grep '^version:' pubspec.yaml | awk '{print $2}')-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/*.apk
          allowUpdates: false
          name: "Release - ${{ steps.date.outputs.date }}"
          body: "Published at ${{ steps.date.outputs.date }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag.outputs.tag }}
